modLoader = "javafml"
loaderVersion = "[34,)"
license = "MIT"

[[mods]]
modId = "paragon"
version = "${version}"
displayName = "Paragon"
displayURL = "kyanitemods.dev"
logoFile = "icon.png"
authors = "Kyanite"

description = '''
Lightweight and easy-to-use config library
'''

[[dependencies.paragon]]
modId = "forge"
mandatory = true
versionRange = "[40.1.86,)"
ordering = "NONE"
side = "BOTH"