name: Java Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: jdk18
          arguments: clean build --no-build-cache
          gradle-version: wrapper
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: "./forge/build/libs"
          name: Forge Jars
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: "./fabric/build/libs"
          name: Fabric Jars
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: "./common/build/libs"
          name: Common Jars