name: Release Workflow

on:
  release:
    types: [published]


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - run: chmod +x gradlew
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: jdk18
          arguments: clean build --no-build-cache
          gradle-version: wrapper
      - name: Release to CurseForge and Modrinth
        uses: gradle/gradle-build-action@v2
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        with:
          arguments: publishUnified --stacktrace --no-daemon